version: '3.8'

services:
  circle-server:
    build:
      context: ./
    container_name: circle-server-container
    restart: always
    expose:
      - 3001
    env_file:
      - .env
    command: sh -c "npm run migrate:up && npm run start"

  nginx:
    image: nginx:alpine
    container_name: nginx-reverse-proxy
    ports:
      - "3001:3001"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - circle-server
